datasets:
  cbt_knowledge_collection:
    description: "[TODO: Agent Description]"
    database_type: "vector"
    files:
      - path: "./data/cbt_knowledge/Cognitive-Behavioral-Therapy-Techniques-and-Strategies-Intro-Sample.pdf"
        type: "pdf"
      - path: "./data/cbt_knowledge/Cognitive_Behavioral_Therapy_Strategies.pdf"
        type: "pdf"
      - path: "./data/cbt_knowledge/therapists_guide_to_brief_cbtmanual.pdf"
        type: "pdf"
      - path: "./data/cbt_knowledge/wellbeing-team-cbt-workshop-booklet-2016.pdf"
        type: "pdf"
  socratic_questioning_collection:
    description: ""
    database_type: "vector"
    files:
      - path: "./data/socratic_questioning/SOCRATIC QUESTIONS.pdf"
        type: "pdf"
      - path: "./data/socratic_questioning/Socratic-Questioning-Techniques.pdf"
        type: "pdf"
      - path: "./data/socratic_questioning/SocraticQuestioning2006.pdf"
        type: "pdf"
  psychotherapy_collection:
    description: ""
    database_type: "graph"
    files:
      - path: "./data/psychotherapy/an_introduction_to_counseling.pdf"
        type: "pdf"
      - path: "./data/psychotherapy/Theory and Practice of Counseling and Psychotherapy- Corey- 9ed.pdf"
        type: "pdf"
      - path: "./data/psychotherapy/What_is_psychotherapy_today_Overview_of_psychother.pdf"
        type: "pdf"
      
options:
  pre_retrieval:
    multi_query_expansion: true
  retrieval_datasets:
    - dataset_name: "cbt_knowledge_collection"
      tool_name: "cognitive_behavioral_therapy_retriever"
      tool_description: "Any question related to Cognitive Behavioral Therapy should use this retriever. Searches general knowledge about cognitive behavioral therapy (CBT) and its techniques."
      format: "Following text chunks divided by new line characters are the CBT techniques and strategies that can be used to help you answer to user's question: {context}"
    - dataset_name: "socratic_questioning_collection"
      tool_name: "socratic_questioning_retriever"
      tool_description: "Before counseling a user, AI should use this retriever to get the best socratic questioning techniques and practices. Searches general knowledge about socratic questioning techniques. Socratic Questioning is a most common CBT method. Any question related to socratic questioning should use this retriever. ."
      format: "Following text chunks divided by new line characters are the Socratic Questioning techniques that can be used to help you answer to user's question: {context}"
  post_retrieval:
    context_top_k: 5
    context_reranking: false
    context_compression: false